#!/bin/bash
C_RUNNER_NAME=""
C_TOKEN_FORMAT="XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
C_TOKEN=""
C_RUNNER_TAR="e0987bc1c2b71e732a0e7963a8a6de64fe3be2a282122c23c52b83d7cebfafdb"
C_RUNNER_TAR_SIZE=140443681
C_TOKEN_SIZE=29
C_RUNNER_ID_SIZE=4
C_ENV_TOKEN_FORMAT_DEF="ENV_TOKEN=$C_TOKEN_FORMAT"
C_ENV_RUNNERS_ID_DEF="ENV_RUNNERS_ID=\"XXX1 XXX2 XXX3\""
C_LABELS="self-hosted,macOS,X64,Ajolotios"
C_ORG="Ajolotios"
C_GROUP="$C_ORG-MacStadium"
D_DOWNLOADS="downloads"
D_RUNNERS="runners"
F_RUNNER_TAR="actions-runner-osx-x64-2.319.1.tar.gz"
F_CONFIG="config.sh"
F_ENV=".env"
S_RUNNER="./src/Runner.sh"
T_MISSING_ID="\n\t❌ Missing runnerID argument"
T_MISSING_TOKEN="\n\t❌ Missing token argument"
T_INVALID_ID="\n\t❌ Invalid runnerID argument"
T_INVALID_TOKEN="\n\t❌ Invalid token argument"
T_MISSING_ENV="\n\t❌ Missing .env file"
T_FILL_ENV="\n\t   File .env was created for you,\n\t   please fill it with your information\n"
T_ID_FORMAT="\n\t\t ◉ runnerID format: XXXX\n"
T_TOKEN_FORMAT="\n\t\t ◉ token format   : $C_TOKEN_FORMAT\n"
URL_DOWNLOAD="https://github.com/actions/runner/releases/download/v2.319.1"
URL_ORG="https://github.com/$C_ORG"
